name: ReadMe Stats Updater

on:
  workflow_run:
    workflows: ["Main ReadMe Updater"]
    branches: [master]
    types: 
      - completed

jobs:
  UpdateStatsTemplate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.USER_TOKEN }}
        template: ./README.md
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "[Automatic] Updated Stats ReadMe.md"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        fi
